### ISSUE TITLE
CF Exporter specifies incorrect deployment name

### ISSUE THREAD

**Issue by thomasmitchell** [genesis-community/prometheus-genesis-kit#10]
We're specifying the CF deployment name as "my-cool-env" instead of "my-cool-env-cf".
https://github.com/genesis-community/prometheus-genesis-kit/blob/6f8d839d5e0f8f50cd9ebcee4c0698509fb3ab87/manifests/monitor-cf.yml#L26

Firehose exporter dashboard uses the deployment names from CF exporter to determine what deployment names it should be looking at for firehose logs. This causes the firehose_exporter related metrics in CF dashboards to come up empty.

We should probably just append "-cf" to the end of the value as a quick and dirty fix.

**Comment by jhunt** [comment]
or just `(( grab name ))`...

**Comment by thomasmitchell** [comment]
Fixed by 4f5a3a9a95d8e12eae04fbc6dc7fc09f5dbc7253
