### ISSUE TITLE
Bug in pre-flight check

### ISSUE THREAD

**Issue by r0bm3** [genesis-community/prometheus-genesis-kit#4]
there is a bug in the pre-flight check for version 1.1.2 (.../dev/hooks/check) on line 20.

is:      if safe --quiet x509 validate "$vault/$cert" --for "$(lookup params.static_ip)"
should be:      if safe --quiet x509 validate "$vault/$cert" --for "$(lookup params.external_domain)"

**Comment by dennisjbell** [comment]
The intention with the kit was that if you're using an external domain, you'd supply your own SSL certificate for it.  The usage of a self-signed certificate was to facilitate those just using an internal static IP.

**Comment by r0bm3** [comment]
Dennis,
We’re not using a self-signed certificate, in fact it is a DigiCert CA signed wildcard cert.

Hope that helps.

Thanks,
Robert Meissner | Sys Engr | JHA Cloud Services - CNI
Jack Henry & Associates, Inc.® | www.jackhenry.com
rmeissner@jackhenry.com | Ph 417-235-8892
________________________________
